app:
  build: './docker'
  restart: always
  command: 'node /www/app/server'
  environment:
    NODE_ENV: 'production'
    LD_LIBRARY_PATH: '/usr/lib/x86_64-linux-gnu'
  volumes:
    - .:/www/app/
  net: 'host'
